---
title: "ReportOptimumQuality"
author: "Nom, Prenom Etudiant GIPI"
date: "01-09-2023"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(qcc)

```

## Ceci est un rapport d'analyse du processus suivi

Ceci peut etre utilisé comme modèle pour la génération d'un rapport automatique personnalisé pour le suivi du processus.

## Graphiques de cartes de controle

```{r data, include=FALSE}
# Generate example data
data(pistonrings) #données example de pistons
#Piston rings for an automotive engine are produced by a forging process. The inside diameter of the rings manufactured by the process is measured on 25 samples, each of size 5, for the control phase I, when preliminary samples from a process being considered 'in control' are used to construct control charts. Then, further 15 samples, again each of size 5, are obtained for phase II.
attach(pistonrings)
diameter <- qcc.groups(diameter, sample)
head(diameter)

```

On peut egalement afficher des graphiques, par exemple:

```{r pressure, echo=FALSE}


# Create X-bar and R charts in French

q1 <- qcc(diameter, type = "xbar", label.limits = c("LCI", "LCS"), title = "Carte de controle", xlab	= "Groupe", ylab	= "Diammetre", lang = "FR")

q2 <- qcc(diameter, type = "R")

```


